### ISSUE TITLE
I can't use them because an error was reported

### ISSUE THREAD

**Issue by Dylan-lijl** [dennis84/codemirror-themes#2]
##version

"dependencies": {
    "@codemirror/lang-xml": "^6.0.2",
    "@ddietr/codemirror-themes": "^1.4.0",
    "codemirror": "^6.0.1",
    "vue": "^3.2.22",
    "vue-codemirror": "^6.1.1",
    "vue-lazyload": "^1.3.3",
    "vue-router": "^4.0.0-0",
    "vuex": "^4.0.0-0",
  },

##code

import { Codemirror } from "vue-codemirror";
import { githubLight } from "@ddietr/codemirror-themes/github-light";
import { githubDark } from "@ddietr/codemirror-themes/github-dark";
import { xml } from "@codemirror/lang-xml";

##error

These dependencies were not found:

* @ddietr/codemirror-themes/github-dark in ./node_modules/cache-loader/dist/cjs.js??ref--13-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--1-0!./node_modules/vue-loader-v16/dist??ref--1-1!./src/views/other/components/SvgEditor.vue?vue&type=script&lang=js
* @ddietr/codemirror-themes/github-light in ./node_modules/cache-loader/dist/cjs.js??ref--13-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--1-0!./node_modules/vue-loader-v16/dist??ref--1-1!./src/views/other/components/SvgEditor.vue?vue&type=script&lang=js

To install them, you can run: npm install --save @ddietr/codemirror-themes/github-dark @ddietr/codemirror-themes/github-light

**Comment by dennis84** [comment]
Hello, i think the mistake was that you used:
```
npm install --save @ddietr/codemirror-themes/github-dark
```
instead of :
```
npm install --save @ddietr/codemirror-themes
```
to install the package.

**Comment by duhbbx** [comment]
Same case: vue3 + vite5 + ts

找不到模块“@ddietr/codemirror-themes/material-light”或其相应的类型声明。ts-plugin(2307)

**Comment by dennis84** [comment]
Unfortunately, I cannot reproduce your problem, i tried it in a new vue project and everything works fine. Which Node and Typescript version are you using?

**Comment by dennis84** [comment]
@duhbbx I had only exported the files as esm, maybe that was the problem here. Could you install version 1.4.4 and see if the problem still exists?
