### ISSUE TITLE
Highlighting selection of text doesn't render highlight over the first line of the selection

### ISSUE THREAD

**Issue by u9g** [dennis84/codemirror-themes#4]
Hi, first of all thank you for developing this, it looks great. When using it, I discovered a small problem described here: https://discuss.codemirror.net/t/basicsetup-breaks-cursor-highlighting/6964/2 Thanks to [marijn](https://discuss.codemirror.net/u/marijn)'s help I was able to figure out that the fix (for github-dark theme) is 
```diff
diff --git a/dist/theme/github-dark.js b/dist/theme/github-dark.js
index 3758dd94146e9434a29d835c59c8e8040544da10..3faefcceab2e060b4020b722dbe1c59bc9ea2323 100644
--- a/dist/theme/github-dark.js
+++ b/dist/theme/github-dark.js
@@ -46,7 +46,7 @@ const githubDarkTheme = EditorView.theme({
     '.cm-searchMatch.cm-searchMatch-selected': {
         backgroundColor: config.selection
     },
-    '.cm-activeLine': { backgroundColor: config.activeLine },
+    '.cm-activeLine': { backgroundColor: 'transparent' },
     '.cm-selectionMatch': { backgroundColor: config.selection },
     '&.cm-focused .cm-matchingBracket, &.cm-focused .cm-nonmatchingBracket': {
         backgroundColor: config.matchingBracket,
```

Although you will probably have to apply this diff to every of your themes.

I can pr it if you don't see any problems with this.

**Comment by dennis84** [comment]
Hi, I'll take a look on that problem...

The colors come from VS code themes and are generated. Some themes have transparent active lines and some not, the active line in github dark is defined as: `"editor.lineHighlightBackground": "#2b3036"`

Setting active line to transparent in all themes doesn't seem to be a good solution to me, you could override that in your CSS for now or disable the highlightActiveLine extension.

What I don't understand why I can't see the problem in my examples:
<img width="388" alt="Bildschirmfoto 2023-08-11 um 19 53 38" src="https://github.com/dennis84/codemirror-themes/assets/353900/c270999a-1e07-4b51-8e64-cd6880bb667c">

**Comment by u9g** [comment]
> What I don't understand why I can't see the problem in my examples:

What browser are you using and on what OS? I could replicate this on edge/firefox on ubuntu mate.

**Comment by dennis84** [comment]
I can see the problem in the link you posted in the forum. But i can't see it in the examples of this repo

**Comment by dennis84** [comment]
But there is a problem with active line and the selection, also in other themes. VS-Code hides the active line if it has selection, this makes the selection invisible because the colors are often very similar. I will try to find a solution for this

**Comment by dennis84** [comment]
The problem with my examples was that i didn't use the drawSelection extension. This extension disables the native browser selection and adds layers behind the text and these layers must have a transparent active line to be visible.

I added a fix that use the background color for the active line with a few modifications: +~10% alpha, +/-20% lightness depending on whether is light or a dark theme. I hope this works better.

https://github.com/dennis84/codemirror-themes/commit/23e54d0f44f214e749d5e58d4a9fd3e6134a6c0a
